
### ------------------------------Auth----------------------------------- ####

### Registrar un usuario
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}

### iniciar sesión para obtener token
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "123456"
}

### verificar token
POST http://localhost:8000/auth/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzIyNzM2NjMsImV4cCI6MTc3MjM2MDA2M30.BWwXWVoH5fweHeVMcq-Jb_OuimU_5VNqLCuWZXawubE

### ------------------------------Tasks----------------------------------- ####

### crear una task
POST http://localhost:8000/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzIyNzM2NjMsImV4cCI6MTc3MjM2MDA2M30.BWwXWVoH5fweHeVMcq-Jb_OuimU_5VNqLCuWZXawubE

{
    "title": "Nueva tarea2",
    "description": "Descripción de la nueva tarea",
    "priority": "Alta",
    "state": "En_Proceso",
    "limit_date": "2024-07-15T12:00:00Z",
    "user_id": "1",
    "category_id": "1"
}

### obtener todas las tasks de un usuario
GET http://localhost:8000/tasks/tasksUser/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzIyNzM2NjMsImV4cCI6MTc3MjM2MDA2M30.BWwXWVoH5fweHeVMcq-Jb_OuimU_5VNqLCuWZXawubE

### obtener numero de tasks de un usuario
GET http://localhost:8000/tasks/taskNumber/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzIyNzM2NjMsImV4cCI6MTc3MjM2MDA2M30.BWwXWVoH5fweHeVMcq-Jb_OuimU_5VNqLCuWZXawubE

### obtener numero de tasks favoritas del usuario
GET http://localhost:8000/tasks/taskNumberFavorites/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI1NzMwNTAsImV4cCI6MTc3MjY1OTQ1MH0.FA-SI01EdJlLSiCrOPJRcOnVR2BxHUmvwd7BvupfJ84

### obtener numero de tasks archivadas del usuario
GET http://localhost:8000/tasks/taskNumberArchived/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI1NzMwNTAsImV4cCI6MTc3MjY1OTQ1MH0.FA-SI01EdJlLSiCrOPJRcOnVR2BxHUmvwd7BvupfJ84


### obtener una task por id
GET http://localhost:8000/tasks/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzIyNzM2NjMsImV4cCI6MTc3MjM2MDA2M30.BWwXWVoH5fweHeVMcq-Jb_OuimU_5VNqLCuWZXawubE

### actualizar una task
PUT http://localhost:8000/tasks/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzIyNzM2NjMsImV4cCI6MTc3MjM2MDA2M30.BWwXWVoH5fweHeVMcq-Jb_OuimU_5VNqLCuWZXawubE

{
    "title": "Tarea actualizada",
    "description": "Descripción actualizada de la tarea",
    "priority": "Media",
    "state": "Completado",
    "limit_date": "2024-07-20T12:00:00Z",
    "category_id": "1"
}

### eliminar una task
DELETE http://localhost:8000/tasks/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzIyNzM2NjMsImV4cCI6MTc3MjM2MDA2M30.BWwXWVoH5fweHeVMcq-Jb_OuimU_5VNqLCuWZXawubE

### ------------------------------Categories----------------------------------- ####

### Crear una categoría
POST http://localhost:8000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI1NzA5NTQsImV4cCI6MTc3MjY1NzM1NH0.zGy8m1Qe6xYx8G7NjbK1M0dsirYl1XfZnE4FeC3Q2bc

{
    "name": "Trabajoo",
    "user_id": "1"
}

### Actualizar una categoría
PUT http://localhost:8000/categories/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI0NjM4NzksImV4cCI6MTc3MjU1MDI3OX0.zoj7eP-mMzI8gdtoIZWs8WJK2Xa-YMrxGmhCUSshEDo

{
    "name": "Trabajaso"
}

### Eliminar una categoria
DELETE http://localhost:8000/categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI0NjM4NzksImV4cCI6MTc3MjU1MDI3OX0.zoj7eP-mMzI8gdtoIZWs8WJK2Xa-YMrxGmhCUSshEDo

### Obtener todas las categorías de un usuario
GET http://localhost:8000/categories/categoriesUser/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI0NjM4NzksImV4cCI6MTc3MjU1MDI3OX0.zoj7eP-mMzI8gdtoIZWs8WJK2Xa-YMrxGmhCUSshEDo

### Obtener una categoría por id
GET http://localhost:8000/categories/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBnbWFpbC5jb20iLCJpYXQiOjE3NzI0NjM4NzksImV4cCI6MTc3MjU1MDI3OX0.zoj7eP-mMzI8gdtoIZWs8WJK2Xa-YMrxGmhCUSshEDo